services:
  - type: web
    name: WayPoint-backend
    env: docker
    repo: https://github.com/savitar2001/WayPoint
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /api/health
    plan: free
    envVarGroups:
      - name: WayPoint-env

  - type: web
    name: WayPoint-frontend
    plan: free
    repo: https://github.com/savitar2001/WayPoint
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 80
    healthCheckPath: /
    envVarGroups:
      - name: WayPoint-env

  - type: worker
    name: WayPoint-queue-worker
    env: docker
    repo: https://github.com/savitar2001/WayPoint
    dockerfilePath: ./backend/Dockerfile
    dockerCommand: "php artisan queue:work redis --sleep=3 --tries=3 --max-time=3600"
    plan: free
    envVarGroups:
      - name: WayPoint-env

  - type: redis
    name: my-redis-cache
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []