services:
  - type: web
    name: WayPoint-backend
    runtime: docker
    repo: https://github.com/savitar2001/WayPoint
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /api/health-check
    plan: free
    envVars:
      - fromGroup: WayPoint-env

  - type: web
    name: WayPoint-frontend
    runtime: node
    plan: free
    repo: https://github.com/savitar2001/WayPoint
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -p $PORT
    healthCheckPath: /
    envVars:
      - fromGroup: WayPoint-env

  - type: redis
    name: my-redis-cache
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []